name: air_bnb_clone
description: A minimal Airbnb-style clone (no Firebase yet)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: "^0.14.4"
  # google_maps_flutter: ^2.3.0
  # geolocator: ^14.0.2
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
    - assets/img/goa.png
    - assets/img/hampi.png
    - assets/img/jaipur.png
    - assets/img/manali.png
    - assets/img/mumbai.png
    - assets/img/munnar.png
    - assets/img/udaipur.png
    - assets/img/varanasi.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/icon.png"




