name: Flutter macOS/iOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
      - run: flutter pub get
      - run: flutter build macos --release

  build-ios-simulatou:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
      - run: flutter pub get
      - run: flutter build ios --simulator
